language: php
sudo: required 
php:
  - '7.1'
before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - composer self-update
  - composer install --no-interaction
  - composer dump-autoload
  - php artisan migrate:refresh --seed
  - php artisan key:generate
  - nvm install 9
  - npm i -g npm
  - yarn
  - npm run dev
cache:
  directories:
    - $HOME/.composer/cache/files